services:
  - type: web
    name: eyeball-tracking
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py"
    region: oregon
    branch: main
    healthCheckPath: "/"
    envVars:
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
      - key: STREAMLIT_SERVER_PORT
        value: "8000"
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: "false"
